<?php

  define('EMC_MODE', CLICSHOPPING_APP_BOXTALE_SERVER);
  define('EMC_USER', CLICSHOPPING_APP_BOXTALE_USER);
  define('EMC_PASS', CLICSHOPPING_APP_BOXTALE_PASSWORD);
  define('EMC_KEY', CLICSHOPPING_APP_BOXTALE_KEY);
